<a href="https://colab.research.google.com/github/dermond0917/SPARK_5/blob/master/howToGetDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!mkdir dataset

In [0]:
!cd dataset
!mkdir 0_real_image
!mkdir 1_gan_generated_image

In [0]:
rmdir 1_gan_generated_image

In [5]:
cd dataset

/content/dataset


In [0]:
!mkdir 0_real_image
!mkdir 1_gan_generated_image

In [1]:
ls

dataset/  sample_data/


In [2]:
cd dataset

/content/dataset


In [3]:
ls

0_real_image/  1_gan_generated_image/


In [4]:
cd 0_real_image

/content/dataset/0_real_image


In [5]:
ls

1-images.jpg  2-images.jpg  4-images.jpg


In [6]:
cd ..

/content/dataset


In [7]:
cd ..

/content


In [0]:
import numpy as np
import os
import cv2
from numpy import array

In [9]:
# x_train = data / y_train = label
x_train = []
y_train = []

TRAIN_DIR = 'dataset/'
train_folder_list = array(os.listdir(TRAIN_DIR))
train_folder_list

array(['0_real_image', '1_gan_generated_image'], dtype='<U21')

In [13]:
for index in range(len(train_folder_list)):
  path = os.path.join(TRAIN_DIR, train_folder_list[index])
  path += '/'
  img_list = os.listdir(path)
  print(img_list)

['2-images.jpg', '4-images.jpg', '1-images.jpg']
['3-images.jpg']


In [16]:
for index in range(len(train_folder_list)):
  path = os.path.join(TRAIN_DIR, train_folder_list[index])
  path += '/'
  img_list = os.listdir(path)
  for img in img_list:
    img_path = os.path.join(path, img) 
    img = cv2.imread(img_path, cv2.IMREAD_COLOR) 
    img = np.reshape(img, -1)
    x_train.append(img) 
    y_train.append(index)
x_train

[array([ 47,  50,  58, ..., 238, 240, 240], dtype=uint8),
 array([217, 208, 204, ..., 158, 147, 167], dtype=uint8),
 array([12, 33, 48, ..., 29, 27, 27], dtype=uint8),
 array([164,  51, 119, ...,  32,  64, 107], dtype=uint8),
 array([ 47,  50,  58, ..., 238, 240, 240], dtype=uint8),
 array([217, 208, 204, ..., 158, 147, 167], dtype=uint8),
 array([12, 33, 48, ..., 29, 27, 27], dtype=uint8),
 array([164,  51, 119, ...,  32,  64, 107], dtype=uint8)]